version: "3.4"
services:
  back_servicio:
    image: backend_pyto_cp_mysql
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./
        target: /app
      - type: volume
        source: nodemodules # name of the volume, see below
        target: /app/node_modules
        volume:
          nocopy: true
    working_dir: /app
    command: npm run dev
    environment:
      - NODE_ENV=development
      - PORT=4000
volumes:
    nodemodules: